name = "WiltonInts84"                                                                                  
uuid = "a3e2863e-c0ee-5ff6-a523-307a4cdc8724"                                                                     
version = "0.2.6" 

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
